# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/troffel/Repos/Vk_Build

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/troffel/Repos/Vk_Build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/troffel/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/troffel/Repos/Vk_Build/CMakeFiles /home/troffel/Repos/Vk_Build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/troffel/Repos/Vk_Build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Vulkan

# Build rule for target.
Vulkan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vulkan
.PHONY : Vulkan

# fast build rule for target.
Vulkan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/build
.PHONY : Vulkan/fast

#=============================================================================
# Target rules for targets named copy_assets

# Build rule for target.
copy_assets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy_assets
.PHONY : copy_assets

# fast build rule for target.
copy_assets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/copy_assets.dir/build.make CMakeFiles/copy_assets.dir/build
.PHONY : copy_assets/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw/CMakeFiles/uninstall.dir/build.make Libraries/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw/src/CMakeFiles/update_mappings.dir/build.make Libraries/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f Libraries/glfw/src/CMakeFiles/glfw.dir/build.make Libraries/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/math/mat.o: src/math/mat.cpp.o
.PHONY : src/math/mat.o

# target to build an object file
src/math/mat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/math/mat.cpp.o
.PHONY : src/math/mat.cpp.o

src/math/mat.i: src/math/mat.cpp.i
.PHONY : src/math/mat.i

# target to preprocess a source file
src/math/mat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/math/mat.cpp.i
.PHONY : src/math/mat.cpp.i

src/math/mat.s: src/math/mat.cpp.s
.PHONY : src/math/mat.s

# target to generate assembly for a file
src/math/mat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/math/mat.cpp.s
.PHONY : src/math/mat.cpp.s

src/math/vec2.o: src/math/vec2.cpp.o
.PHONY : src/math/vec2.o

# target to build an object file
src/math/vec2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/math/vec2.cpp.o
.PHONY : src/math/vec2.cpp.o

src/math/vec2.i: src/math/vec2.cpp.i
.PHONY : src/math/vec2.i

# target to preprocess a source file
src/math/vec2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/math/vec2.cpp.i
.PHONY : src/math/vec2.cpp.i

src/math/vec2.s: src/math/vec2.cpp.s
.PHONY : src/math/vec2.s

# target to generate assembly for a file
src/math/vec2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/math/vec2.cpp.s
.PHONY : src/math/vec2.cpp.s

src/math/vec3.o: src/math/vec3.cpp.o
.PHONY : src/math/vec3.o

# target to build an object file
src/math/vec3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/math/vec3.cpp.o
.PHONY : src/math/vec3.cpp.o

src/math/vec3.i: src/math/vec3.cpp.i
.PHONY : src/math/vec3.i

# target to preprocess a source file
src/math/vec3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/math/vec3.cpp.i
.PHONY : src/math/vec3.cpp.i

src/math/vec3.s: src/math/vec3.cpp.s
.PHONY : src/math/vec3.s

# target to generate assembly for a file
src/math/vec3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/math/vec3.cpp.s
.PHONY : src/math/vec3.cpp.s

src/paths.o: src/paths.cpp.o
.PHONY : src/paths.o

# target to build an object file
src/paths.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/paths.cpp.o
.PHONY : src/paths.cpp.o

src/paths.i: src/paths.cpp.i
.PHONY : src/paths.i

# target to preprocess a source file
src/paths.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/paths.cpp.i
.PHONY : src/paths.cpp.i

src/paths.s: src/paths.cpp.s
.PHONY : src/paths.s

# target to generate assembly for a file
src/paths.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/paths.cpp.s
.PHONY : src/paths.cpp.s

src/player/VillagerStats.o: src/player/VillagerStats.cpp.o
.PHONY : src/player/VillagerStats.o

# target to build an object file
src/player/VillagerStats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/player/VillagerStats.cpp.o
.PHONY : src/player/VillagerStats.cpp.o

src/player/VillagerStats.i: src/player/VillagerStats.cpp.i
.PHONY : src/player/VillagerStats.i

# target to preprocess a source file
src/player/VillagerStats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/player/VillagerStats.cpp.i
.PHONY : src/player/VillagerStats.cpp.i

src/player/VillagerStats.s: src/player/VillagerStats.cpp.s
.PHONY : src/player/VillagerStats.s

# target to generate assembly for a file
src/player/VillagerStats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/player/VillagerStats.cpp.s
.PHONY : src/player/VillagerStats.cpp.s

src/scene_data.o: src/scene_data.cpp.o
.PHONY : src/scene_data.o

# target to build an object file
src/scene_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/scene_data.cpp.o
.PHONY : src/scene_data.cpp.o

src/scene_data.i: src/scene_data.cpp.i
.PHONY : src/scene_data.i

# target to preprocess a source file
src/scene_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/scene_data.cpp.i
.PHONY : src/scene_data.cpp.i

src/scene_data.s: src/scene_data.cpp.s
.PHONY : src/scene_data.s

# target to generate assembly for a file
src/scene_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/scene_data.cpp.s
.PHONY : src/scene_data.cpp.s

src/scene_handler.o: src/scene_handler.cpp.o
.PHONY : src/scene_handler.o

# target to build an object file
src/scene_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/scene_handler.cpp.o
.PHONY : src/scene_handler.cpp.o

src/scene_handler.i: src/scene_handler.cpp.i
.PHONY : src/scene_handler.i

# target to preprocess a source file
src/scene_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/scene_handler.cpp.i
.PHONY : src/scene_handler.cpp.i

src/scene_handler.s: src/scene_handler.cpp.s
.PHONY : src/scene_handler.s

# target to generate assembly for a file
src/scene_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/scene_handler.cpp.s
.PHONY : src/scene_handler.cpp.s

src/vk/drawing/gra_command_buffers.o: src/vk/drawing/gra_command_buffers.cpp.o
.PHONY : src/vk/drawing/gra_command_buffers.o

# target to build an object file
src/vk/drawing/gra_command_buffers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_command_buffers.cpp.o
.PHONY : src/vk/drawing/gra_command_buffers.cpp.o

src/vk/drawing/gra_command_buffers.i: src/vk/drawing/gra_command_buffers.cpp.i
.PHONY : src/vk/drawing/gra_command_buffers.i

# target to preprocess a source file
src/vk/drawing/gra_command_buffers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_command_buffers.cpp.i
.PHONY : src/vk/drawing/gra_command_buffers.cpp.i

src/vk/drawing/gra_command_buffers.s: src/vk/drawing/gra_command_buffers.cpp.s
.PHONY : src/vk/drawing/gra_command_buffers.s

# target to generate assembly for a file
src/vk/drawing/gra_command_buffers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_command_buffers.cpp.s
.PHONY : src/vk/drawing/gra_command_buffers.cpp.s

src/vk/drawing/gra_drawing.o: src/vk/drawing/gra_drawing.cpp.o
.PHONY : src/vk/drawing/gra_drawing.o

# target to build an object file
src/vk/drawing/gra_drawing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_drawing.cpp.o
.PHONY : src/vk/drawing/gra_drawing.cpp.o

src/vk/drawing/gra_drawing.i: src/vk/drawing/gra_drawing.cpp.i
.PHONY : src/vk/drawing/gra_drawing.i

# target to preprocess a source file
src/vk/drawing/gra_drawing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_drawing.cpp.i
.PHONY : src/vk/drawing/gra_drawing.cpp.i

src/vk/drawing/gra_drawing.s: src/vk/drawing/gra_drawing.cpp.s
.PHONY : src/vk/drawing/gra_drawing.s

# target to generate assembly for a file
src/vk/drawing/gra_drawing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_drawing.cpp.s
.PHONY : src/vk/drawing/gra_drawing.cpp.s

src/vk/drawing/gra_flight.o: src/vk/drawing/gra_flight.cpp.o
.PHONY : src/vk/drawing/gra_flight.o

# target to build an object file
src/vk/drawing/gra_flight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_flight.cpp.o
.PHONY : src/vk/drawing/gra_flight.cpp.o

src/vk/drawing/gra_flight.i: src/vk/drawing/gra_flight.cpp.i
.PHONY : src/vk/drawing/gra_flight.i

# target to preprocess a source file
src/vk/drawing/gra_flight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_flight.cpp.i
.PHONY : src/vk/drawing/gra_flight.cpp.i

src/vk/drawing/gra_flight.s: src/vk/drawing/gra_flight.cpp.s
.PHONY : src/vk/drawing/gra_flight.s

# target to generate assembly for a file
src/vk/drawing/gra_flight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_flight.cpp.s
.PHONY : src/vk/drawing/gra_flight.cpp.s

src/vk/drawing/gra_framebuffers.o: src/vk/drawing/gra_framebuffers.cpp.o
.PHONY : src/vk/drawing/gra_framebuffers.o

# target to build an object file
src/vk/drawing/gra_framebuffers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_framebuffers.cpp.o
.PHONY : src/vk/drawing/gra_framebuffers.cpp.o

src/vk/drawing/gra_framebuffers.i: src/vk/drawing/gra_framebuffers.cpp.i
.PHONY : src/vk/drawing/gra_framebuffers.i

# target to preprocess a source file
src/vk/drawing/gra_framebuffers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_framebuffers.cpp.i
.PHONY : src/vk/drawing/gra_framebuffers.cpp.i

src/vk/drawing/gra_framebuffers.s: src/vk/drawing/gra_framebuffers.cpp.s
.PHONY : src/vk/drawing/gra_framebuffers.s

# target to generate assembly for a file
src/vk/drawing/gra_framebuffers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/drawing/gra_framebuffers.cpp.s
.PHONY : src/vk/drawing/gra_framebuffers.cpp.s

src/vk/gra_setup.o: src/vk/gra_setup.cpp.o
.PHONY : src/vk/gra_setup.o

# target to build an object file
src/vk/gra_setup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/gra_setup.cpp.o
.PHONY : src/vk/gra_setup.cpp.o

src/vk/gra_setup.i: src/vk/gra_setup.cpp.i
.PHONY : src/vk/gra_setup.i

# target to preprocess a source file
src/vk/gra_setup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/gra_setup.cpp.i
.PHONY : src/vk/gra_setup.cpp.i

src/vk/gra_setup.s: src/vk/gra_setup.cpp.s
.PHONY : src/vk/gra_setup.s

# target to generate assembly for a file
src/vk/gra_setup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/gra_setup.cpp.s
.PHONY : src/vk/gra_setup.cpp.s

src/vk/pipeline/gra_multisampling.o: src/vk/pipeline/gra_multisampling.cpp.o
.PHONY : src/vk/pipeline/gra_multisampling.o

# target to build an object file
src/vk/pipeline/gra_multisampling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_multisampling.cpp.o
.PHONY : src/vk/pipeline/gra_multisampling.cpp.o

src/vk/pipeline/gra_multisampling.i: src/vk/pipeline/gra_multisampling.cpp.i
.PHONY : src/vk/pipeline/gra_multisampling.i

# target to preprocess a source file
src/vk/pipeline/gra_multisampling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_multisampling.cpp.i
.PHONY : src/vk/pipeline/gra_multisampling.cpp.i

src/vk/pipeline/gra_multisampling.s: src/vk/pipeline/gra_multisampling.cpp.s
.PHONY : src/vk/pipeline/gra_multisampling.s

# target to generate assembly for a file
src/vk/pipeline/gra_multisampling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_multisampling.cpp.s
.PHONY : src/vk/pipeline/gra_multisampling.cpp.s

src/vk/pipeline/gra_pipeline.o: src/vk/pipeline/gra_pipeline.cpp.o
.PHONY : src/vk/pipeline/gra_pipeline.o

# target to build an object file
src/vk/pipeline/gra_pipeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_pipeline.cpp.o
.PHONY : src/vk/pipeline/gra_pipeline.cpp.o

src/vk/pipeline/gra_pipeline.i: src/vk/pipeline/gra_pipeline.cpp.i
.PHONY : src/vk/pipeline/gra_pipeline.i

# target to preprocess a source file
src/vk/pipeline/gra_pipeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_pipeline.cpp.i
.PHONY : src/vk/pipeline/gra_pipeline.cpp.i

src/vk/pipeline/gra_pipeline.s: src/vk/pipeline/gra_pipeline.cpp.s
.PHONY : src/vk/pipeline/gra_pipeline.s

# target to generate assembly for a file
src/vk/pipeline/gra_pipeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_pipeline.cpp.s
.PHONY : src/vk/pipeline/gra_pipeline.cpp.s

src/vk/pipeline/gra_render_passes.o: src/vk/pipeline/gra_render_passes.cpp.o
.PHONY : src/vk/pipeline/gra_render_passes.o

# target to build an object file
src/vk/pipeline/gra_render_passes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_render_passes.cpp.o
.PHONY : src/vk/pipeline/gra_render_passes.cpp.o

src/vk/pipeline/gra_render_passes.i: src/vk/pipeline/gra_render_passes.cpp.i
.PHONY : src/vk/pipeline/gra_render_passes.i

# target to preprocess a source file
src/vk/pipeline/gra_render_passes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_render_passes.cpp.i
.PHONY : src/vk/pipeline/gra_render_passes.cpp.i

src/vk/pipeline/gra_render_passes.s: src/vk/pipeline/gra_render_passes.cpp.s
.PHONY : src/vk/pipeline/gra_render_passes.s

# target to generate assembly for a file
src/vk/pipeline/gra_render_passes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_render_passes.cpp.s
.PHONY : src/vk/pipeline/gra_render_passes.cpp.s

src/vk/pipeline/gra_shader.o: src/vk/pipeline/gra_shader.cpp.o
.PHONY : src/vk/pipeline/gra_shader.o

# target to build an object file
src/vk/pipeline/gra_shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_shader.cpp.o
.PHONY : src/vk/pipeline/gra_shader.cpp.o

src/vk/pipeline/gra_shader.i: src/vk/pipeline/gra_shader.cpp.i
.PHONY : src/vk/pipeline/gra_shader.i

# target to preprocess a source file
src/vk/pipeline/gra_shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_shader.cpp.i
.PHONY : src/vk/pipeline/gra_shader.cpp.i

src/vk/pipeline/gra_shader.s: src/vk/pipeline/gra_shader.cpp.s
.PHONY : src/vk/pipeline/gra_shader.s

# target to generate assembly for a file
src/vk/pipeline/gra_shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/pipeline/gra_shader.cpp.s
.PHONY : src/vk/pipeline/gra_shader.cpp.s

src/vk/presentation/gra_image_views.o: src/vk/presentation/gra_image_views.cpp.o
.PHONY : src/vk/presentation/gra_image_views.o

# target to build an object file
src/vk/presentation/gra_image_views.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/presentation/gra_image_views.cpp.o
.PHONY : src/vk/presentation/gra_image_views.cpp.o

src/vk/presentation/gra_image_views.i: src/vk/presentation/gra_image_views.cpp.i
.PHONY : src/vk/presentation/gra_image_views.i

# target to preprocess a source file
src/vk/presentation/gra_image_views.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/presentation/gra_image_views.cpp.i
.PHONY : src/vk/presentation/gra_image_views.cpp.i

src/vk/presentation/gra_image_views.s: src/vk/presentation/gra_image_views.cpp.s
.PHONY : src/vk/presentation/gra_image_views.s

# target to generate assembly for a file
src/vk/presentation/gra_image_views.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/presentation/gra_image_views.cpp.s
.PHONY : src/vk/presentation/gra_image_views.cpp.s

src/vk/presentation/gra_surface.o: src/vk/presentation/gra_surface.cpp.o
.PHONY : src/vk/presentation/gra_surface.o

# target to build an object file
src/vk/presentation/gra_surface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/presentation/gra_surface.cpp.o
.PHONY : src/vk/presentation/gra_surface.cpp.o

src/vk/presentation/gra_surface.i: src/vk/presentation/gra_surface.cpp.i
.PHONY : src/vk/presentation/gra_surface.i

# target to preprocess a source file
src/vk/presentation/gra_surface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/presentation/gra_surface.cpp.i
.PHONY : src/vk/presentation/gra_surface.cpp.i

src/vk/presentation/gra_surface.s: src/vk/presentation/gra_surface.cpp.s
.PHONY : src/vk/presentation/gra_surface.s

# target to generate assembly for a file
src/vk/presentation/gra_surface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/presentation/gra_surface.cpp.s
.PHONY : src/vk/presentation/gra_surface.cpp.s

src/vk/presentation/gra_swap_chain.o: src/vk/presentation/gra_swap_chain.cpp.o
.PHONY : src/vk/presentation/gra_swap_chain.o

# target to build an object file
src/vk/presentation/gra_swap_chain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/presentation/gra_swap_chain.cpp.o
.PHONY : src/vk/presentation/gra_swap_chain.cpp.o

src/vk/presentation/gra_swap_chain.i: src/vk/presentation/gra_swap_chain.cpp.i
.PHONY : src/vk/presentation/gra_swap_chain.i

# target to preprocess a source file
src/vk/presentation/gra_swap_chain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/presentation/gra_swap_chain.cpp.i
.PHONY : src/vk/presentation/gra_swap_chain.cpp.i

src/vk/presentation/gra_swap_chain.s: src/vk/presentation/gra_swap_chain.cpp.s
.PHONY : src/vk/presentation/gra_swap_chain.s

# target to generate assembly for a file
src/vk/presentation/gra_swap_chain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/presentation/gra_swap_chain.cpp.s
.PHONY : src/vk/presentation/gra_swap_chain.cpp.s

src/vk/setup/gra_debug.o: src/vk/setup/gra_debug.cpp.o
.PHONY : src/vk/setup/gra_debug.o

# target to build an object file
src/vk/setup/gra_debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_debug.cpp.o
.PHONY : src/vk/setup/gra_debug.cpp.o

src/vk/setup/gra_debug.i: src/vk/setup/gra_debug.cpp.i
.PHONY : src/vk/setup/gra_debug.i

# target to preprocess a source file
src/vk/setup/gra_debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_debug.cpp.i
.PHONY : src/vk/setup/gra_debug.cpp.i

src/vk/setup/gra_debug.s: src/vk/setup/gra_debug.cpp.s
.PHONY : src/vk/setup/gra_debug.s

# target to generate assembly for a file
src/vk/setup/gra_debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_debug.cpp.s
.PHONY : src/vk/setup/gra_debug.cpp.s

src/vk/setup/gra_instance.o: src/vk/setup/gra_instance.cpp.o
.PHONY : src/vk/setup/gra_instance.o

# target to build an object file
src/vk/setup/gra_instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_instance.cpp.o
.PHONY : src/vk/setup/gra_instance.cpp.o

src/vk/setup/gra_instance.i: src/vk/setup/gra_instance.cpp.i
.PHONY : src/vk/setup/gra_instance.i

# target to preprocess a source file
src/vk/setup/gra_instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_instance.cpp.i
.PHONY : src/vk/setup/gra_instance.cpp.i

src/vk/setup/gra_instance.s: src/vk/setup/gra_instance.cpp.s
.PHONY : src/vk/setup/gra_instance.s

# target to generate assembly for a file
src/vk/setup/gra_instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_instance.cpp.s
.PHONY : src/vk/setup/gra_instance.cpp.s

src/vk/setup/gra_logical_device.o: src/vk/setup/gra_logical_device.cpp.o
.PHONY : src/vk/setup/gra_logical_device.o

# target to build an object file
src/vk/setup/gra_logical_device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_logical_device.cpp.o
.PHONY : src/vk/setup/gra_logical_device.cpp.o

src/vk/setup/gra_logical_device.i: src/vk/setup/gra_logical_device.cpp.i
.PHONY : src/vk/setup/gra_logical_device.i

# target to preprocess a source file
src/vk/setup/gra_logical_device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_logical_device.cpp.i
.PHONY : src/vk/setup/gra_logical_device.cpp.i

src/vk/setup/gra_logical_device.s: src/vk/setup/gra_logical_device.cpp.s
.PHONY : src/vk/setup/gra_logical_device.s

# target to generate assembly for a file
src/vk/setup/gra_logical_device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_logical_device.cpp.s
.PHONY : src/vk/setup/gra_logical_device.cpp.s

src/vk/setup/gra_physical_device.o: src/vk/setup/gra_physical_device.cpp.o
.PHONY : src/vk/setup/gra_physical_device.o

# target to build an object file
src/vk/setup/gra_physical_device.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_physical_device.cpp.o
.PHONY : src/vk/setup/gra_physical_device.cpp.o

src/vk/setup/gra_physical_device.i: src/vk/setup/gra_physical_device.cpp.i
.PHONY : src/vk/setup/gra_physical_device.i

# target to preprocess a source file
src/vk/setup/gra_physical_device.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_physical_device.cpp.i
.PHONY : src/vk/setup/gra_physical_device.cpp.i

src/vk/setup/gra_physical_device.s: src/vk/setup/gra_physical_device.cpp.s
.PHONY : src/vk/setup/gra_physical_device.s

# target to generate assembly for a file
src/vk/setup/gra_physical_device.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_physical_device.cpp.s
.PHONY : src/vk/setup/gra_physical_device.cpp.s

src/vk/setup/gra_queue_families.o: src/vk/setup/gra_queue_families.cpp.o
.PHONY : src/vk/setup/gra_queue_families.o

# target to build an object file
src/vk/setup/gra_queue_families.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_queue_families.cpp.o
.PHONY : src/vk/setup/gra_queue_families.cpp.o

src/vk/setup/gra_queue_families.i: src/vk/setup/gra_queue_families.cpp.i
.PHONY : src/vk/setup/gra_queue_families.i

# target to preprocess a source file
src/vk/setup/gra_queue_families.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_queue_families.cpp.i
.PHONY : src/vk/setup/gra_queue_families.cpp.i

src/vk/setup/gra_queue_families.s: src/vk/setup/gra_queue_families.cpp.s
.PHONY : src/vk/setup/gra_queue_families.s

# target to generate assembly for a file
src/vk/setup/gra_queue_families.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/setup/gra_queue_families.cpp.s
.PHONY : src/vk/setup/gra_queue_families.cpp.s

src/vk/shading/gra_depth.o: src/vk/shading/gra_depth.cpp.o
.PHONY : src/vk/shading/gra_depth.o

# target to build an object file
src/vk/shading/gra_depth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_depth.cpp.o
.PHONY : src/vk/shading/gra_depth.cpp.o

src/vk/shading/gra_depth.i: src/vk/shading/gra_depth.cpp.i
.PHONY : src/vk/shading/gra_depth.i

# target to preprocess a source file
src/vk/shading/gra_depth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_depth.cpp.i
.PHONY : src/vk/shading/gra_depth.cpp.i

src/vk/shading/gra_depth.s: src/vk/shading/gra_depth.cpp.s
.PHONY : src/vk/shading/gra_depth.s

# target to generate assembly for a file
src/vk/shading/gra_depth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_depth.cpp.s
.PHONY : src/vk/shading/gra_depth.cpp.s

src/vk/shading/gra_memory_utils.o: src/vk/shading/gra_memory_utils.cpp.o
.PHONY : src/vk/shading/gra_memory_utils.o

# target to build an object file
src/vk/shading/gra_memory_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_memory_utils.cpp.o
.PHONY : src/vk/shading/gra_memory_utils.cpp.o

src/vk/shading/gra_memory_utils.i: src/vk/shading/gra_memory_utils.cpp.i
.PHONY : src/vk/shading/gra_memory_utils.i

# target to preprocess a source file
src/vk/shading/gra_memory_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_memory_utils.cpp.i
.PHONY : src/vk/shading/gra_memory_utils.cpp.i

src/vk/shading/gra_memory_utils.s: src/vk/shading/gra_memory_utils.cpp.s
.PHONY : src/vk/shading/gra_memory_utils.s

# target to generate assembly for a file
src/vk/shading/gra_memory_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_memory_utils.cpp.s
.PHONY : src/vk/shading/gra_memory_utils.cpp.s

src/vk/shading/gra_uniform.o: src/vk/shading/gra_uniform.cpp.o
.PHONY : src/vk/shading/gra_uniform.o

# target to build an object file
src/vk/shading/gra_uniform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_uniform.cpp.o
.PHONY : src/vk/shading/gra_uniform.cpp.o

src/vk/shading/gra_uniform.i: src/vk/shading/gra_uniform.cpp.i
.PHONY : src/vk/shading/gra_uniform.i

# target to preprocess a source file
src/vk/shading/gra_uniform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_uniform.cpp.i
.PHONY : src/vk/shading/gra_uniform.cpp.i

src/vk/shading/gra_uniform.s: src/vk/shading/gra_uniform.cpp.s
.PHONY : src/vk/shading/gra_uniform.s

# target to generate assembly for a file
src/vk/shading/gra_uniform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_uniform.cpp.s
.PHONY : src/vk/shading/gra_uniform.cpp.s

src/vk/shading/gra_vertex.o: src/vk/shading/gra_vertex.cpp.o
.PHONY : src/vk/shading/gra_vertex.o

# target to build an object file
src/vk/shading/gra_vertex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_vertex.cpp.o
.PHONY : src/vk/shading/gra_vertex.cpp.o

src/vk/shading/gra_vertex.i: src/vk/shading/gra_vertex.cpp.i
.PHONY : src/vk/shading/gra_vertex.i

# target to preprocess a source file
src/vk/shading/gra_vertex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_vertex.cpp.i
.PHONY : src/vk/shading/gra_vertex.cpp.i

src/vk/shading/gra_vertex.s: src/vk/shading/gra_vertex.cpp.s
.PHONY : src/vk/shading/gra_vertex.s

# target to generate assembly for a file
src/vk/shading/gra_vertex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/gra_vertex.cpp.s
.PHONY : src/vk/shading/gra_vertex.cpp.s

src/vk/shading/model.o: src/vk/shading/model.cpp.o
.PHONY : src/vk/shading/model.o

# target to build an object file
src/vk/shading/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/model.cpp.o
.PHONY : src/vk/shading/model.cpp.o

src/vk/shading/model.i: src/vk/shading/model.cpp.i
.PHONY : src/vk/shading/model.i

# target to preprocess a source file
src/vk/shading/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/model.cpp.i
.PHONY : src/vk/shading/model.cpp.i

src/vk/shading/model.s: src/vk/shading/model.cpp.s
.PHONY : src/vk/shading/model.s

# target to generate assembly for a file
src/vk/shading/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/model.cpp.s
.PHONY : src/vk/shading/model.cpp.s

src/vk/shading/texture.o: src/vk/shading/texture.cpp.o
.PHONY : src/vk/shading/texture.o

# target to build an object file
src/vk/shading/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/texture.cpp.o
.PHONY : src/vk/shading/texture.cpp.o

src/vk/shading/texture.i: src/vk/shading/texture.cpp.i
.PHONY : src/vk/shading/texture.i

# target to preprocess a source file
src/vk/shading/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/texture.cpp.i
.PHONY : src/vk/shading/texture.cpp.i

src/vk/shading/texture.s: src/vk/shading/texture.cpp.s
.PHONY : src/vk/shading/texture.s

# target to generate assembly for a file
src/vk/shading/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/vk/shading/texture.cpp.s
.PHONY : src/vk/shading/texture.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vulkan.dir/build.make CMakeFiles/Vulkan.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... copy_assets"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... Vulkan"
	@echo "... glfw"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/math/mat.o"
	@echo "... src/math/mat.i"
	@echo "... src/math/mat.s"
	@echo "... src/math/vec2.o"
	@echo "... src/math/vec2.i"
	@echo "... src/math/vec2.s"
	@echo "... src/math/vec3.o"
	@echo "... src/math/vec3.i"
	@echo "... src/math/vec3.s"
	@echo "... src/paths.o"
	@echo "... src/paths.i"
	@echo "... src/paths.s"
	@echo "... src/player/VillagerStats.o"
	@echo "... src/player/VillagerStats.i"
	@echo "... src/player/VillagerStats.s"
	@echo "... src/scene_data.o"
	@echo "... src/scene_data.i"
	@echo "... src/scene_data.s"
	@echo "... src/scene_handler.o"
	@echo "... src/scene_handler.i"
	@echo "... src/scene_handler.s"
	@echo "... src/vk/drawing/gra_command_buffers.o"
	@echo "... src/vk/drawing/gra_command_buffers.i"
	@echo "... src/vk/drawing/gra_command_buffers.s"
	@echo "... src/vk/drawing/gra_drawing.o"
	@echo "... src/vk/drawing/gra_drawing.i"
	@echo "... src/vk/drawing/gra_drawing.s"
	@echo "... src/vk/drawing/gra_flight.o"
	@echo "... src/vk/drawing/gra_flight.i"
	@echo "... src/vk/drawing/gra_flight.s"
	@echo "... src/vk/drawing/gra_framebuffers.o"
	@echo "... src/vk/drawing/gra_framebuffers.i"
	@echo "... src/vk/drawing/gra_framebuffers.s"
	@echo "... src/vk/gra_setup.o"
	@echo "... src/vk/gra_setup.i"
	@echo "... src/vk/gra_setup.s"
	@echo "... src/vk/pipeline/gra_multisampling.o"
	@echo "... src/vk/pipeline/gra_multisampling.i"
	@echo "... src/vk/pipeline/gra_multisampling.s"
	@echo "... src/vk/pipeline/gra_pipeline.o"
	@echo "... src/vk/pipeline/gra_pipeline.i"
	@echo "... src/vk/pipeline/gra_pipeline.s"
	@echo "... src/vk/pipeline/gra_render_passes.o"
	@echo "... src/vk/pipeline/gra_render_passes.i"
	@echo "... src/vk/pipeline/gra_render_passes.s"
	@echo "... src/vk/pipeline/gra_shader.o"
	@echo "... src/vk/pipeline/gra_shader.i"
	@echo "... src/vk/pipeline/gra_shader.s"
	@echo "... src/vk/presentation/gra_image_views.o"
	@echo "... src/vk/presentation/gra_image_views.i"
	@echo "... src/vk/presentation/gra_image_views.s"
	@echo "... src/vk/presentation/gra_surface.o"
	@echo "... src/vk/presentation/gra_surface.i"
	@echo "... src/vk/presentation/gra_surface.s"
	@echo "... src/vk/presentation/gra_swap_chain.o"
	@echo "... src/vk/presentation/gra_swap_chain.i"
	@echo "... src/vk/presentation/gra_swap_chain.s"
	@echo "... src/vk/setup/gra_debug.o"
	@echo "... src/vk/setup/gra_debug.i"
	@echo "... src/vk/setup/gra_debug.s"
	@echo "... src/vk/setup/gra_instance.o"
	@echo "... src/vk/setup/gra_instance.i"
	@echo "... src/vk/setup/gra_instance.s"
	@echo "... src/vk/setup/gra_logical_device.o"
	@echo "... src/vk/setup/gra_logical_device.i"
	@echo "... src/vk/setup/gra_logical_device.s"
	@echo "... src/vk/setup/gra_physical_device.o"
	@echo "... src/vk/setup/gra_physical_device.i"
	@echo "... src/vk/setup/gra_physical_device.s"
	@echo "... src/vk/setup/gra_queue_families.o"
	@echo "... src/vk/setup/gra_queue_families.i"
	@echo "... src/vk/setup/gra_queue_families.s"
	@echo "... src/vk/shading/gra_depth.o"
	@echo "... src/vk/shading/gra_depth.i"
	@echo "... src/vk/shading/gra_depth.s"
	@echo "... src/vk/shading/gra_memory_utils.o"
	@echo "... src/vk/shading/gra_memory_utils.i"
	@echo "... src/vk/shading/gra_memory_utils.s"
	@echo "... src/vk/shading/gra_uniform.o"
	@echo "... src/vk/shading/gra_uniform.i"
	@echo "... src/vk/shading/gra_uniform.s"
	@echo "... src/vk/shading/gra_vertex.o"
	@echo "... src/vk/shading/gra_vertex.i"
	@echo "... src/vk/shading/gra_vertex.s"
	@echo "... src/vk/shading/model.o"
	@echo "... src/vk/shading/model.i"
	@echo "... src/vk/shading/model.s"
	@echo "... src/vk/shading/texture.o"
	@echo "... src/vk/shading/texture.i"
	@echo "... src/vk/shading/texture.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

